[package]
name = "rust-kit"
version = "0.1.0"
edition = "2021"
description = "Rust tool kit"
license = "GPL-3.0"
repository = "https://github.com/ryqdev/rust_utils"
authors = ["ryqdev"]

[dependencies]
